version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: "" # Required by dependabot
    password: "" # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/dependencyManagement"
    ignore:
      - dependency-name: "org.slf4j:*"
        # moving to 2.0 is problematic because the SPI mechanism in 2.0 doesn't work in the
        # bootstrap class loader because, while we add the agent jar to the bootstrap class loader
        # via Instrumentation.appendToBootstrapClassLoaderSearch(), there's nothing similar for
        # resources (which is a known problem in the java agent world), and so the META-INF/services
        # resource is not found
        versions: [ "2.x" ]
      - dependency-name: "com.squareup.moshi:*"
        versions: [ "[1.12.0,)" ]
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/"
    allow:
      - dependency-name: "com.gradle*"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
