version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: "" # Required by dependabot
    password: "" # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/dependencyManagement"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/"
    allow:
      - dependency-name: "com.gradle*"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
