version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: "" # Required by dependabot
    password: "" # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    ignore:
      - dependency-name: "ch.qos.logback:*"
        # logback 1.4+ requires Java 11+
        versions: [ "[1.4,)" ]
      - dependency-name: "com.squareup.moshi:*"
        # 1.12.0 and above use okio 2.x which pulls in kotlin libs (which are large)
        versions: [ "[1.12,)" ]
      - dependency-name: "org.springframework.boot:spring-boot-gradle-plugin"
        # this is used for smoke tests
        # spring boot 3 requires Java 17, and we're not ready yet
        versions: [ "[3,)" ]
      - dependency-name: "javax.servlet:javax.servlet-api"
        # applicationinsights-web (classic sdk) is intentionally compiled and against Servlet 3.0
        versions: [ "[3.1,)" ]
      - dependency-name: "org.eclipse.jetty:jetty-servlet"
        # smoke test framework intentionally uses javax servlet (as opposed to jakarta servlet)
        versions: [ "[11,)" ]
      - dependency-name: "org.mockito:*"
        # mockito 5 requires Java 11
        versions: [ "[5,)" ]
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
