path_classifiers:
  submodule:
    - otel
extraction:
  java:
    index:
      java_version: 11
      build_command: |
        # needs Java 11, otherwise this could be done in before_index
        ./otel/gradlew --project-dir otel/gradle-plugins publishToMavenLocal
        ./otel/gradlew --project-dir otel publishToMavenLocal
        ./gradlew --no-daemon testClasses
