path_classifiers:
  submodule:
    - otel
extraction:
  java:
    index:
      java_version: 11
      build_command: |
        # needs Java 11, otherwise this could be done in before_index
        # javadoc fails sporadically fetching https://docs.oracle.com/javase/8/docs/api/
        ./otel/gradlew --project-dir otel publishToMavenLocal -x javadoc
        ./gradlew --no-daemon testClasses
