name: Build (common)

on:
  workflow_call:
    inputs:
      no-build-cache:
        type: boolean
        required: false

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ":smoke-tests:apps:PreAggMetricsWithRoleNameOverridesAndSampling"
          - ":smoke-tests:apps:PreAggMetricsWithRoleNameOverridesAndSampling"
          - ":smoke-tests:apps:PreAggMetricsWithRoleNameOverridesAndSampling"
          - ":smoke-tests:apps:PreAggMetricsWithRoleNameOverridesAndSampling"
          - ":smoke-tests:apps:PreAggMetricsWithRoleNameOverridesAndSampling"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Using a local standalone exporter dependency?
        if: ${{ hashFiles('azure-monitor-opentelemetry-exporter-1.0.0-beta.*.jar') != '' }}
        run: |
          echo "exporter_version: ${{ env.EXPORTER_VERSION }}"
          mvn -version
          mvn install:install-file -Dfile="azure-monitor-opentelemetry-exporter-${{ env.EXPORTER_VERSION }}.jar" -DpomFile="azure-monitor-opentelemetry-exporter-${{ env.EXPORTER_VERSION }}.pom" -DgroupId="com.azure" -DartifactId="azure-monitor-opentelemetry-exporter" -Dversion="${{ env.EXPORTER_VERSION }}"

      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ matrix.module }}:smokeTest
