name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/build-common.yml

  test-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: |
          ./gradlew test clean

  required-status-check:
    needs:
      - common
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: needs.common.result != 'success'
        run: exit 1
