name: Build (daily)

on:
  schedule:
    # strange schedule to reduce the risk of DDOS GitHub infra
    - cron: "24 3 * * *"
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
