name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  license-check:
    uses: ./.github/workflows/reusable-license-check.yml

  assemble:
    uses: ./.github/workflows/reusable-assemble.yml

  test:
    uses: ./.github/workflows/reusable-test.yml

  smoke-test:
    uses: ./.github/workflows/reusable-smoke-test.yml

  required-status-check:
    needs:
      - assemble
      - test
      - smoke-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.assemble.result != 'success' ||
          needs.test.result != 'success' ||
          needs.smoke-test.result != 'success'
        run: exit 1
