name: CI build

on:
  push:
    branches:
      - main
      - vnext

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-latest ]
      fail-fast: false
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        if: matrix.os == 'windows-2019'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check assemble

      - name: Upload snapshot
        # only upload from windows since only that build includes etw
        if: matrix.os == 'windows-2019'
        uses: actions/upload-artifact@v3
        with:
          path: agent/agent/build/libs/applicationinsights-agent-*-SNAPSHOT.jar

  setup-smoke-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: set-matrix
        run: |
          modules=$(ls -d smoke-tests/apps/* | sed 's/\/$//' | sed 's/\//:/g' | sed 's/^/:/')
          inner_json=$(echo $modules | xargs echo | sed 's/ /","/g')
          echo "::set-output name=matrix::{\"module\":[\"$inner_json\"]}"

  smoke-test:
    needs: setup-smoke-test-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup-smoke-test-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.module }}:smokeTest
