name: Daily performance test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:

  assemble-application-insights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

  perf-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17

    - name: Perf test folder
      run: cd perf-tests

    - name: Run perf test
      env:
        PERF_TEST_URL_PATTERN: ${{ secrets.PERF_TEST_URL_PATTERN }}
      run: ./gradlew test
