name: PR build

on:
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
          - ":test:smoke:testApps:OpenTelemetryApiSupport"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Init and update otel submodule
        run: |
          git submodule init
          git submodule update
      - name: Restore cache
        uses: burrunan/gradle-cache-action@v1
        with:
          read-only: true
      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build otel-fork
        working-directory: otel
        # javadoc fails sporadically fetching https://docs.oracle.com/javase/8/docs/api/
        run: ./gradlew publishToMavenLocal -x javadoc --stacktrace
      - name: Test
        # TODO enable build cache, either --build-cache here, or org.gradle.caching=true in gradle.properties
        run: ./gradlew ${{ matrix.module }}:smokeTest
