name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          version=$(.github/scripts/get-version.sh)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          # CHANGELOG_SECTION.md is also used at the end of the release workflow
          # for copying the change log updates to main
          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
            > /tmp/CHANGELOG_SECTION.md

          # the complex perl regex is needed because markdown docs render newlines as soft wraps
          # while release notes render them as line breaks
          perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' /tmp/CHANGELOG_SECTION.md \
            >> /tmp/release-notes.txt

      - id: create-github-release
        name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $VERSION != *-BETA* ]]
          then
            GA=" (GA)"
          fi
          curl -o applicationinsights-agent-$VERSION.jar \
                  https://repo1.maven.org/maven2/com/microsoft/azure/applicationinsights-agent/$VERSION/applicationinsights-agent-$VERSION.jar
          gh release create --target main \
                            --title "Version $VERSION$GA" \
                            --notes-file /tmp/release-notes.txt \
                            --draft \
                            $VERSION \
                            applicationinsights-agent-$VERSION.jar
