name: Reusable - Assemble

on:
  workflow_call:
    inputs:
      no-build-cache:
        type: boolean
        required: false

jobs:
  assemble:
    # running (and uploading artifact) from windows since only that build includes etw
    runs-on: windows-2019
    steps:
      - name: Support long paths
        run: git config --system core.longpaths true

      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          # javadoc task fails sporadically fetching https://docs.oracle.com/javase/8/docs/api/
          arguments: assemble -x javadoc ${{ inputs.no-build-cache && '--no-build-cache' || '' }}

      - name: Upload snapshot
        uses: actions/upload-artifact@v3
        with:
          path: agent/agent/build/libs/applicationinsights-agent-*-SNAPSHOT.jar
