name: Reusable - Smoke test

on:
  workflow_call:
    inputs:
      no-build-cache:
        type: boolean
        required: false

jobs:
  setup-smoke-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: |
          modules=$(ls -d smoke-tests/apps/* | sed 's/\/$//' | sed 's/\//:/g' | sed 's/^/:/')
          inner_json=$(echo $modules | xargs echo | sed 's/ /","/g')
          echo "::set-output name=matrix::{\"module\":[\"$inner_json\"]}"

  smoke-test:
    needs: setup-smoke-test-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup-smoke-test-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.module }}:smokeTest
